FROM python:3.9-alpine3.14

# Create a group and user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN /usr/local/bin/python -m pip install --upgrade pip

ENV PATH=$PATH:"/home/appuser/.local/bin"
# Tell docker that all future commands should run as the appuser user
USER appuser
RUN pip install sphinx sphinx-rtd-theme sphinx_autodoc_typehints
